# Get installation environment variables
get_env_vars() {
  env | grep -E "^(OMARCHY_CHROOT_INSTALL|OMARCHY_ONLINE_INSTALL|OMARCHY_RETRY_INSTALL|OMARCHY_USER_NAME|OMARCHY_USER_EMAIL|USER|HOME|OMARCHY_REPO|OMARCHY_REF|OMARCHY_PATH|OMARCHY_INSTALL|OMARCHY_ARM|ASAHI_ALARM|OMARCHY_VIRTUALIZATION|OMARCHY_VMWARE|OMARCHY_VM_SOFTWARE_RENDERING|OMARCHY_SKIP_LIMINE|OMARCHY_SIMULATE_AUR_DOWN|OMARCHY_SIMULATE_MIRROR_DOWN|SKIP_YARU|SKIP_OBS|SKIP_PINTA)=" | sort
}
